version: '3.1'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #   - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432